server:
  port: 8000

spring:
  # dev|test|prod
  profiles:
#    active: @spring.profiles.active@
    active: dev

mybatis:
  mapper-locations: classpath:mapping/*.xml

secure:
  ignored-url:
    - /**/*.css
    - /**/*.png
    - /**/*.ico


jwt:
  # 令牌前缀
  token-header: Authorization
  # 令牌前缀
  token-head: 'Bearer '
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=

  expiration: 60

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
#      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
#      keyConvertor: fastjson
#      java,kryo
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379